apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot-service.fullname" . }}
  labels:
  {{- include "springboot-service.labels" . | nindent 4 }}
  {{- if .Values.config.labels }}
  {{- toYaml .Values.config.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.config.annotations }}
  annotations:
    {{- toYaml .Values.config.annotations | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.config.log4j }}
  logging.yaml: >-
    {{- tpl . $ | nindent 4 }}
    {{- end }}
  {{- with .Values.config.application }}
  application.yaml: >-
    {{- tpl . $ | nindent 4 }}
  {{- end }}