image:
  registry: "ghcr.io"
  repository: "scoolee/example-service"
  tag: "0.0.12"
  pullPolicy: IfNotPresent

replicaCount: 1

ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: http-management
    containerPort: 9090
    protocol: TCP

livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/liveness
    port: "http-management"
  failureThreshold: 3
  periodSeconds: 15

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/readiness
    port: "http-management"
  failureThreshold: 10
  periodSeconds: 15

startupProbe:
  enabled: true
  httpGet:
    path: /actuator/health/readiness
    port: "http-management"
  failureThreshold: 10
  initialDelaySeconds: 15
  periodSeconds: 15

podRestartPolicy: Always

podSecurityContext:
  enabled: false
  fsGroup: 0

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: true

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
  
envVars:
  LOG4J_CONFIGURATION_FILE: "/etc/config/app/log4j.yaml"
  JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0 -Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Dspring.config.additional-location=/etc/config/app/application.yaml"

autoscaling:
  enabled: false

configMap:
  mounted: true
  mountPath: "/etc/config/app"
  data:
    log4j.yaml: |-
      Configuration:
        Appenders:
          Console:
            name: Console
            target: SYSTEM_OUT
            JsonLayout:
              compact: true
              eventEol: true
              includeTimeMillis: true

        Loggers:
          Root:
            level: INFO
            AppenderRef:
              - ref: Console
    application.yaml: |-
      management:
        server:
          port: 9090
        endpoint:
          health:
            probes:
              enabled: true
            livenessState:
              enabled: true
            readinessState:
              enabled: true

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp

ingress:
  enabled: false

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

serviceAccount:
  create: true
  automountServiceAccountToken: true
